/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class air_eclipse_Main */

#ifndef _Included_air_eclipse_Main
#define _Included_air_eclipse_Main
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
