/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class playjni_Main */

#ifndef _Included_playjni_Main
#define _Included_playjni_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     playjni_Main
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_playjni_Main_printHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
